# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout the current branch
        run: |
          echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
          git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
          git fetch --unshallow --tags
          git tag
          if [[ $(git rev-parse --abbrev-ref HEAD) == "master" ]]; then
              echo "reattaching HEAD on master"
              git symbolic-ref --short HEAD || git checkout -b ${GITHUB_ENV}-test $GITHUB_ENV
          fi

          sudo apt update -q
          # Install additional GTK/GObject development packages needed for building
          sudo apt-get install --no-install-recommends -y \
            libgirepository1.0-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            libvte-2.91-dev \
            libwnck-3-dev \
            libkeybinder-3.0-dev \
            libnotify-dev \
            libcairo2-dev \
            pkg-config \
            meson \
            ninja-build
          yes | sudo ./scripts/bootstrap-dev-debian.sh
          ./scripts/bootstrap-dev-pip.sh system

          export DISPLAY=:99.0

      - name: Test with pytest
        run: |
          set -e
          mkdir test-rtd
          virtualenv test-rtd
          . ./test-rtd/bin/activate
          pip install -r requirements-dev.txt

          # for dev
          make dev-actions
          pipenv run pip install pycairo pygobject platformdirs importlib_metadata
          # check
          make check
          make build
          make test-actions
          # prepare for deployment
          make generate-paths
          rm -rf test-rtd

      - name: Store dists (Python 3.9)
        if: matrix.python-version == '3.9'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build
    steps:
      - name: Retrieve dists
        uses: actions/download-artifact@v4
        with:
          path: ./
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verify-metadata: false
          verbose: true
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
